// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXKPVmIy6oyohnBYMJ5ATDcuEEU81vNoA',
    appId: '1:572364594195:web:4351731c6ee3abe2aa33e6',
    messagingSenderId: '572364594195',
    projectId: 'donut-app-hector-2c',
    authDomain: 'donut-app-hector-2c.firebaseapp.com',
    storageBucket: 'donut-app-hector-2c.firebasestorage.app',
    measurementId: 'G-G7K5VMPD8G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7YkQLYoTcLYlLglOnILbfqX5rUbFYybE',
    appId: '1:572364594195:android:fab1d8d92bb68b96aa33e6',
    messagingSenderId: '572364594195',
    projectId: 'donut-app-hector-2c',
    storageBucket: 'donut-app-hector-2c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6uUqVHxzVuNCeeP70daUynHP3ZpyoJ0o',
    appId: '1:572364594195:ios:0443619f6cfe5e11aa33e6',
    messagingSenderId: '572364594195',
    projectId: 'donut-app-hector-2c',
    storageBucket: 'donut-app-hector-2c.firebasestorage.app',
    iosBundleId: 'com.example.donutApp2cHector',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6uUqVHxzVuNCeeP70daUynHP3ZpyoJ0o',
    appId: '1:572364594195:ios:0443619f6cfe5e11aa33e6',
    messagingSenderId: '572364594195',
    projectId: 'donut-app-hector-2c',
    storageBucket: 'donut-app-hector-2c.firebasestorage.app',
    iosBundleId: 'com.example.donutApp2cHector',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXKPVmIy6oyohnBYMJ5ATDcuEEU81vNoA',
    appId: '1:572364594195:web:c08aa320cade6032aa33e6',
    messagingSenderId: '572364594195',
    projectId: 'donut-app-hector-2c',
    authDomain: 'donut-app-hector-2c.firebaseapp.com',
    storageBucket: 'donut-app-hector-2c.firebasestorage.app',
    measurementId: 'G-86DSQGN33S',
  );
}
